### PR TITLE
Support Go to Definition requests for labels in string literals

### PR DESCRIPTION
**Pull request by withered-magic**
Adds the equivalent of the functionality described in https://github.com/bazelbuild/vscode-bazel/pull/380

### CODE REVIEW

**Comment by sluongng** [comment]
hmm does this work?

I tested it with BuildBuddy.git and Bazel.git, both cannot do `Go to Def` for most target labels. For example:

```
gazelle_binary(
    name = "bb_gazelle_binary",
    languages = DEFAULT_LANGUAGES + ["@bazel_gazelle//language/bazel/visibility:go_default_library"],
)
```

trying to "go to def" on `"@bazel_gazelle//language/bazel/visibility:go_default_library"` would fail.

**Comment by withered-magic** [comment]
Ah sorry, forgot to clarify that this is specifically for source files! e.g. `//path/to/source.cc`

**Comment by withered-magic** [comment]
Just updated this PR description to indicate this, and opened https://github.com/withered-magic/starpls/issues/203 to track the remaining functionality!

**Comment by sluongng** [comment]
I don't think it works. For example, I tried it on this line https://github.com/buildbuddy-io/buildbuddy/blob/bb4c9d9ff75ace7c549819e40cac080414a6a226/server/buildbuddy_server/BUILD#L71 and it did not open the Go file.

Also I think it's typical to have source syntax in the form of `//some/package:local/package/path.ext` and/or `local/package/path.ext` for short.

**Comment by withered-magic** [comment]
Hmm, I was able to get it working from that file for all the various forms of source syntax that you mentioned:

https://github.com/withered-magic/starpls/assets/153045167/e4fac38f-794f-4609-8d6a-e376aa64d5a3

This functionality isn't actually on a release yet, are you using a custom build from latest `main`?

**Comment by sluongng** [comment]
ah I built from the latest from main, but I copied the old binary from `editors/code/bin/starpls` instead of directly from my `bazel-out`. 😮‍💨 

sorry for the noise

**Comment by withered-magic** [comment]
no worries!

**Comment by withered-magic** [comment]
Goto def for non-source file labels hasbeen added in https://github.com/withered-magic/starpls/pull/205!

**Comment by sluongng** [comment]
Amazing! I love starpls already!

**Pull request merged**
